# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0541b19ed21bdcd66138936ab71e679d949972cdac3786c69d1c6185fc9bb8c3faac26b962b9cc5ba73a6ff6d1459b62d43b6833759d89d4081e927ce58f422

test:
  secret_key_base: 22190b99176ab14e246c3cfbe9450d37fbcb3dd03e7cc9635fead79ac862bc174e3e3ce75ca4188f08c5932f37cf01592904ea7e63ed3744b65d074f00394be9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
